# Generated by Django 3.0.5 on 2020-05-27 08:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='FAQ内容')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'tn_faq',
            },
        ),
    ]
