# Generated by Django 3.0.5 on 2020-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
