# Generated by Django 3.0.5 on 2020-05-27 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_blog_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
