# Generated by Django 3.0.5 on 2020-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_blog_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Blog时间'),
        ),
    ]
