# Generated by Django 3.0.5 on 2020-04-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200425_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Nav', verbose_name='上级菜单'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
