# Generated by Django 3.0.5 on 2020-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200504_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('order', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=500, verbose_name='横幅标题')),
                ('link', models.CharField(max_length=500, verbose_name='横幅链接')),
                ('image_url', models.ImageField(blank=True, max_length=255, null=True, upload_to='banner', verbose_name='横幅图片')),
            ],
            options={
                'verbose_name': '横幅广告',
                'verbose_name_plural': '横幅广告',
                'db_table': 'tn_main_banner',
            },
        ),
    ]
