# Generated by Django 3.0.5 on 2020-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mainbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='position',
            field=models.IntegerField(choices=[(1, '上面的横幅'), (2, '下面的横幅')], default=1, verbose_name='横幅所属位置'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='main_banner', verbose_name='横幅图片'),
        ),
    ]
