# Generated by Django 3.0.5 on 2020-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_centerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='客户姓名')),
                ('email', models.CharField(max_length=500, verbose_name='客户邮箱')),
                ('msg', models.TextField(verbose_name='客户留言')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'db_table': 'tn_message',
            },
        ),
    ]
