# Generated by Django 3.0.5 on 2020-05-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否推新'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_url', to='products.Products', verbose_name='所属产品'),
        ),
    ]
