# Generated by Django 3.0.5 on 2020-05-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_message_created_time'),
        ('products', '0003_auto_20200526_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='general_category',
            field=models.ForeignKey(default=5, limit_choices_to={'position': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Nav', verbose_name='所属大类'),
            preserve_default=False,
        ),
    ]
